from fastapi import FastAPI
from pydantic import BaseModel
import os
from dotenv import load_dotenv
import torch

try:
    import google.generativeai as genai
except Exception:
    genai = None

# Removed Hugging Face dependencies - using Gemini only

load_dotenv = lambda: None
try:
    from dotenv import load_dotenv as _ld
    _ld()
except Exception:
    pass

# Configure Gemini (preferred)
gemini_api_key = os.getenv('GOOGLE_API_KEY') or 'AIzaSyC2vCvUu3PL6KtVwWA4ZSaFYf283VMSFUs'
gemini_model = None
if genai is not None and gemini_api_key:
    try:
        genai.configure(api_key=gemini_api_key)
        gemini_model = genai.GenerativeModel('gemini-2.0-flash')
    except Exception as _e:
        gemini_model = None

app = FastAPI(title='Suggestion Agent (Gemini Only)')

class Inp(BaseModel):
    feedback: str
    themes: str
    entities: list[str] = []

@app.post('/suggest')
async def suggest(inp: Inp):
    def rule_based():
        fb = inp.feedback.lower()
        sugs = []
        if 'stress' in fb or 'overtime' in fb or 'late' in fb:
            sugs.append('Introduce stress management and review workload allocation.')
        if 'salary' in fb or 'pay' in fb:
            sugs.append('Consider reviewing compensation and communicate pay policy clearly.')
        if not sugs:
            sugs.append('Encourage better communication between managers and staff; collect more detail.')
        return {'suggestions': sugs, 'rationale': 'Rule-based fallback', 'model_used': 'Rule-based'}

# Removed Hugging Face suggestion function - using Gemini only

    def gemini_suggest():
        if gemini_model is None:
            return None
        try:
            prompt = (
                "You are an HR assistant. Given employee feedback, themes, and entities, "
                "produce 3 concise, actionable, and ethical suggestions. Avoid identifying individuals or biased language. "
                "Return ONLY a JSON object with fields 'suggestions' (array of 3 strings) and 'rationale' (string).\n\n"
                f"Feedback: {inp.feedback}\nThemes: {inp.themes}\nEntities: {', '.join(inp.entities)}"
            )
            resp = gemini_model.generate_content(prompt)
            text = (resp.text or '').strip()
            import json
            try:
                data = json.loads(text)
            except Exception:
                # Try to extract JSON block heuristically
                import re
                match = re.search(r"\{[\s\S]*\}", text)
                data = json.loads(match.group(0)) if match else None
            if isinstance(data, dict) and 'suggestions' in data:
                # Ensure max 3
                data['suggestions'] = data.get('suggestions', [])[:3]
                if not data.get('rationale'):
                    data['rationale'] = 'Generated by Gemini AI'
                data['model_used'] = 'Gemini'
                return data
        except Exception:
            return None

    # Use Gemini first
    g = gemini_suggest()
    if g is not None:
        return g

    # Final fallback to rule-based
    return rule_based()

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8003)
